name: Deploy Lambda Automatically

on:
  push:
    paths:
      - '*/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lambda_dir: [lambda-hello-world]  # Agrega más nombres aquí cuando tengas más lambdas

    if: contains(github.event.head_commit.message, matrix.lambda_dir)

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install and package Lambda
        working-directory: ${{ matrix.lambda_dir }}
        run: |
          mkdir -p package
          pip install -r requirements.txt -t package
          cp *.py package/
          cd package && zip -r ../${{ matrix.lambda_dir }}.zip .

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name ${{ matrix.lambda_dir }} \
            --zip-file fileb://${{ matrix.lambda_dir }}.zip \
            --region us-east-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
